#!/bin/sh

# Set these paths appropriately

BIN=/Users/diegomoussallem/Downloads/tree-tagger-MacOSX-3.2/bin
CMD=/Users/diegomoussallem/Downloads/tree-tagger-MacOSX-3.2/cmd
LIB=/Users/diegomoussallem/Downloads/tree-tagger-MacOSX-3.2/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/finnish-abbreviations-utf8
PARFILE=${LIB}/finnish-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
# tagging
$TAGGER $OPTIONS $PARFILE

