#!/bin/sh

# Set these paths appropriately

BIN=/Users/diegomoussallem/Downloads/tree-tagger-MacOSX-3.2/bin
CMD=/Users/diegomoussallem/Downloads/tree-tagger-MacOSX-3.2/cmd
LIB=/Users/diegomoussallem/Downloads/tree-tagger-MacOSX-3.2/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
